export enum QueryKeys {
  ALL_TRANSACTIONS_WITH_LOGS_ENABLED = 'ALL_TRANSACTIONS_WITH_LOGS_ENABLED',
  ALL_PENDING_ACTIONS = 'ALL_PENDING_ACTIONS',
  FETCHED_DELEGATIONS = 'FETCHED_DELEGATIONS',
  FETCHED_PROVIDERS = 'FETCHED_PROVIDERS',
  FETCHED_PROVIDER_IDENTITIES = 'FETCHED_PROVIDER_IDENTITIES',
  TOKEN_PRICES = 'TOKEN_PRICES',
}
