export enum LOCAL_STORAGE_KEYS {
  PINNED_APPS = 'PINNED_APPS',
  INSTALLED_APPS = 'INSTALLED_APPS',
  UPLOADED_ABI_TEXT = 'UPLOADED_ABI_TEXT',
  SC_INTERACTIONS_ADDRESS = 'SC_INTERACTIONS_ADDRESS',
}
