name: multisig-test

on:
  workflow_dispatch:
  pull_request:
    branches: [develop, master]

jobs:
  test:
    runs-on: [self-hosted, graffino]
    env:
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        node: [14]

    steps:
      - uses: act10ns/slack@v1
        with:
          status: starting
        if: always()

      - name: Checkout
        id: Checkout
        uses: actions/checkout@master
        with:
          ref: 'develop'
        if: success()

      - name: Create .env
        run: |
          awk -v EXTRAS_API_DEVNET="${{ secrets.EXTRAS_API_DEVNET }}" \
              -v MAIAR_ID_API_DEVNET="${{ secrets.MAIAR_ID_API_DEVNET }}" \
              -v UNIQUE_CONTRACT_ADDRESS="${{ secrets.UNIQUE_CONTRACT_ADDRESS }}" \
              -v UNIQUE_CONTRACT_NAME="${{ secrets.UNIQUE_CONTRACT_NAME }}" \
              -v NPM_AUTH_TOKEN="${{ secrets.NPMRC }}" \
              '{ \
                  sub(/XXX_EXTRAS_API_DEVNET_XXX/, EXTRAS_API_DEVNET); \
                  sub(/XXX_MAIAR_ID_API_DEVNET_XXX/, MAIAR_ID_API_DEVNET); \
                  sub(/XXX_UNIQUE_CONTRACT_ADDRESS_XXX/, UNIQUE_CONTRACT_ADDRESS); \
                  sub(/XXX_UNIQUE_CONTRACT_NAME_XXX/, UNIQUE_CONTRACT_NAME); \
                  sub(/XXX_NPM_AUTH_TOKEN_XXX/, NPM_AUTH_TOKEN); \
                  print; \
              }' \
              .env.staging > .env

      - name: Config setup
        run: |
          make setup-wallet

      - uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: YARN Install
        id: YARN-Install
        if: success()
        run: yarn --network-timeout 500000

      # - name: Lint
      #   id: Lint
      #   if: success()
      #   run: |
      #     yarn lint

      - name: Build
        id: Build
        if: success()
        run: |
          export NODE_OPTIONS="--max-old-space-size=2048"
          export CI=false
          export DISABLE_ESLINT_PLUGIN=true
          yarn build

      - uses: act10ns/slack@v1.2.2
        if: always()
        with:
          status: ${{ job.status }}
          steps: ${{ toJson(steps) }}
